
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Frame1 extends javax.swing.JInternalFrame {
    private DefaultListModel<String> listModel; 
    private DefaultListModel<String> detailModel;
    private int nomor = 1;

   
    public Frame1() {
        initComponents();
        listModel = new DefaultListModel<>();
        detailModel = new DefaultListModel<>();
        eList.setModel(listModel);
        eList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            eListValueChanged(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LbDeadline = new javax.swing.JLabel();
        LbNama = new javax.swing.JLabel();
        Detail = new javax.swing.JLabel();
        eNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        eDetail = new javax.swing.JTextArea();
        bClear = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        eDeadline = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        eList = new javax.swing.JList<>();
        LbDaftar = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        eText = new javax.swing.JTextArea();
        bBersihkan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tambah Tugas Baru");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        LbDeadline.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LbDeadline.setText("Deadline Tugas ");
        jPanel5.add(LbDeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        LbNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LbNama.setText("Nama Mata Kuliah");
        jPanel5.add(LbNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        Detail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Detail.setText("Detail Tugas");
        jPanel5.add(Detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel5.add(eNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 240, -1));

        eDetail.setColumns(20);
        eDetail.setRows(5);
        jScrollPane1.setViewportView(eDetail);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 400, -1));

        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        jPanel5.add(bClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel5.add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));
        jPanel5.add(eDeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 240, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg2 (1).jpg"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("Tambah Tugas", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                eListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(eList);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, 180));

        LbDaftar.setText("Detail Tugas");
        jPanel6.add(LbDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        eText.setColumns(20);
        eText.setRows(5);
        jScrollPane3.setViewportView(eText);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 240, 180));

        bBersihkan.setText("Bersihkan");
        bBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBersihkanActionPerformed(evt);
            }
        });
        jPanel6.add(bBersihkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Daftar Tugas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg2 (1).jpg"))); // NOI18N
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("Daftar Tugas", jPanel6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
                                        
        String matkul = eNama.getText();
        java.util.Date deadlineDate = eDeadline.getDate();
        String detail = eDetail.getText();

        if (matkul.isEmpty() || deadlineDate == null || detail.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lengkapi data!!", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String deadline = dateFormat.format(deadlineDate);
            String namaDanTugas = nomor + ". " + matkul + " (dl: " + deadline + ")";
            listModel.addElement(namaDanTugas);
            detailModel.addElement(detail);
            nomor++;
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBersihkanActionPerformed
        int[] selectedIndices = eList.getSelectedIndices();
    
    if (selectedIndices.length > 0) {
        for (int i = selectedIndices.length - 1; i >= 0; i--) {
            listModel.removeElementAt(selectedIndices[i]);
            detailModel.removeElementAt(selectedIndices[i]);
        }

        for (int i = 0; i < listModel.getSize(); i++) {
            String existingItem = listModel.getElementAt(i);
            String[] parts = existingItem.split("\\. ");
            int existingNomor = i + 1;
            String newItem = existingNomor + ". " + parts[1];
            listModel.setElementAt(newItem, i);
        }
        eText.setText("");
        nomor = 1;
        }else if (listModel.isEmpty() || detailModel == null || detailModel.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Lengkapi Daftar Tugas Terlebih Dahulu!!", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else {
            listModel.removeAllElements();
            detailModel.removeAllElements();
            eText.setText("");
            nomor = 1;  
        }
    }//GEN-LAST:event_bBersihkanActionPerformed

    private void eListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_eListValueChanged
        if (!evt.getValueIsAdjusting()) {
            int selectedIndex = eList.getSelectedIndex();
            if (selectedIndex != -1) {
                String detail = detailModel.getElementAt(selectedIndex); 
                eText.setText(detail);
            }
        }
    }//GEN-LAST:event_eListValueChanged

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        eNama.setText("");
        eDeadline.setDate(null);
        eDetail.setText("");
    }//GEN-LAST:event_bClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Detail;
    private javax.swing.JLabel LbDaftar;
    private javax.swing.JLabel LbDeadline;
    private javax.swing.JLabel LbNama;
    private javax.swing.JButton bBersihkan;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bSimpan;
    private com.toedter.calendar.JDateChooser eDeadline;
    private javax.swing.JTextArea eDetail;
    private javax.swing.JList<String> eList;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextArea eText;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
